
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

knx: !include knx.yaml
buderus: !include heat_pump.yaml
sensor: !include sensors.yaml
satel_integra: !include satel.yaml
